ALTER TABLE jobs ADD COLUMN IF NOT EXISTS avg_memory_bytes BIGINT;
ALTER TABLE jobs
  ADD COLUMN IF NOT EXISTS pod_created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS run_started_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS avg_memory_bytes BIGINT;