apiVersion: v1
kind: ServiceAccount
metadata:
  name: solver
  namespace: jobstar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: solver-label
  namespace: jobstar
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: solver-label
  namespace: jobstar
subjects:
  - kind: ServiceAccount
    name: solver
    namespace: jobstar
roleRef:
  kind: Role
  name: solver-label
  apiGroup: rbac.authorization.k8s.io